### ISSUE TITLE
branch_properties key "number" exists?

### ISSUE THREAD

**Issue by mcyc** [e-koch/FilFinder#46]
I don't think values associated with the key "number" was typically generated for `branch_properties`. This is an issue when it comes to executing the following line:

https://github.com/e-koch/FilFinder/blob/81b6012fc81b3bacbea24b4668cc3e75fa7dd637/fil_finder/length.py#L600

Note: the "number" values are not a part of the `branch_properties` returned by `init_lengths()`: https://github.com/e-koch/FilFinder/blob/81b6012fc81b3bacbea24b4668cc3e75fa7dd637/fil_finder/length.py#L127

**Comment by e-koch** [comment]
Hi @mcyc -- You're right, and I think the issue is that `init_lengths` was never being used on its own. `branch_properties['number']` is getting set after calling `init_lengths`: https://github.com/e-koch/FilFinder/blob/master/fil_finder/filament.py#L264 (there's a similar line in the old `fil_finder_2D`). Setting the number of branches in `init_lengths` does make more sense.

Is this causing an error for you when running `FilFinder2D`?

**Comment by e-koch** [comment]
Added a fix in #47
