### ISSUE TITLE
Longest path starting from the left

### ISSUE THREAD

**Issue by pmdnhd** [e-koch/FilFinder#69]
Hi,

Thanks for the package, it is great! I was wondering if it was possible to compute the longest path starting from the most left hand point in the graph (cf 2nd image instead of having 3rd image)? 1st image is the original filament.

Thanks

![filament](https://user-images.githubusercontent.com/32365794/143284300-19af3d1f-9bf6-44d6-a90a-428b3cf77880.png)
![left_longest_path](https://user-images.githubusercontent.com/32365794/143284301-ae8e249b-94d3-457f-a890-b6c2cd8b17d8.png)
![longest_path](https://user-images.githubusercontent.com/32365794/143284302-b02ae27c-1d53-4d50-b3cf-846172c9fb6f.png)

**Comment by e-koch** [comment]
Hi @pmdnhd -- Apologies for the delay!

In short, it wouldn't be straightforward since the longest path isn't conditioned on other properties.

If a sort of by-hand approach could work, I would suggest trying to directly modify the graph connectivity to delete the connection leading to the 3rd image to force the 2nd image case. The graph can be accessed in `Filament2D.graph`, and the connection deleted with `graph.remove_edge` (https://networkx.org/documentation/stable/reference/classes/generated/networkx.Graph.remove_edge.html).

**Comment by pmdnhd** [comment]
Thanks for the answer! I was looking for an automatic way, I will dig a bit more into graphs with networkx, thanks for the suggestion
